
#ifndef __ACINPUTENUMS_H
#define __ACINPUTENUMS_H

enum ACMOUSEBUTTON
{
	ACMOUSE_LEFT         =0x00,
	ACMOUSE_MIDDLE       =0x01,
	ACMOUSE_RIGHT        =0x02
};

enum ACKEYS
{
	ACKEY_BACK           =0x08,
	ACKEY_TAB            =0x09,
	ACKEY_CLEAR          =0x0C,
	ACKEY_RETURN         =0x0D,
	ACKEY_SHIFT          =0x10,
	ACKEY_CONTROL        =0x11,
	ACKEY_MENU           =0x12,
	ACKEY_PAUSE          =0x13,
	ACKEY_CAPITAL        =0x14,
	ACKEY_KANA           =0x15,
	ACKEY_HANGEUL        =0x15,  
	ACKEY_HANGUL         =0x15,
	ACKEY_JUNJA          =0x17,
	ACKEY_FINAL          =0x18,
	ACKEY_HANJA          =0x19,
	ACKEY_KANJI          =0x19,
	ACKEY_ESCAPE         =0x1B,
	ACKEY_CONVERT        =0x1C,
	ACKEY_NONCONVERT     =0x1D,
	ACKEY_ACCEPT         =0x1E,
	ACKEY_MODECHANGE     =0x1F,
	ACKEY_SPACE          =0x20,
	ACKEY_PRIOR          =0x21,
	ACKEY_NEXT           =0x22,
	ACKEY_END            =0x23,
	ACKEY_HOME           =0x24,
	ACKEY_LEFT           =0x25,
	ACKEY_UP             =0x26,
	ACKEY_RIGHT          =0x27,
	ACKEY_DOWN           =0x28,
	ACKEY_SELECT         =0x29,
	ACKEY_PRINT          =0x2A,
	ACKEY_EXECUTE        =0x2B,
	ACKEY_SNAPSHOT       =0x2C,
	ACKEY_INSERT         =0x2D,
	ACKEY_DELETE         =0x2E,
	ACKEY_HELP           =0x2F,
	ACKEY_SLEEP          =0x5F,
	ACKEY_NUMPAD0        =0x60,
	ACKEY_NUMPAD1        =0x61,
	ACKEY_NUMPAD2        =0x62,
	ACKEY_NUMPAD3        =0x63,
	ACKEY_NUMPAD4        =0x64,
	ACKEY_NUMPAD5        =0x65,
	ACKEY_NUMPAD6        =0x66,
	ACKEY_NUMPAD7        =0x67,
	ACKEY_NUMPAD8        =0x68,
	ACKEY_NUMPAD9        =0x69,
	ACKEY_MULTIPLY       =0x6A,
	ACKEY_ADD            =0x6B,
	ACKEY_SEPARATOR      =0x6C,
	ACKEY_SUBTRACT       =0x6D,
	ACKEY_DECIMAL        =0x6E,
	ACKEY_DIVIDE         =0x6F,
	ACKEY_F1             =0x70,
	ACKEY_F2             =0x71,
	ACKEY_F3             =0x72,
	ACKEY_F4             =0x73,
	ACKEY_F5             =0x74,
	ACKEY_F6             =0x75,
	ACKEY_F7             =0x76,
	ACKEY_F8             =0x77,
	ACKEY_F9             =0x78,
	ACKEY_F10            =0x79,
	ACKEY_F11            =0x7A,
	ACKEY_F12            =0x7B,
	ACKEY_F13            =0x7C,
	ACKEY_F14            =0x7D,
	ACKEY_F15            =0x7E,
	ACKEY_F16            =0x7F,
	ACKEY_F17            =0x80,
	ACKEY_F18            =0x81,
	ACKEY_F19            =0x82,
	ACKEY_F20            =0x83,
	ACKEY_F21            =0x84,
	ACKEY_F22            =0x85,
	ACKEY_F23            =0x86,
	ACKEY_F24            =0x87,
						 	  
	ACKEY_MINUS          =0x0C,
	ACKEY_EQUALS         =0x0D,
	ACKEY_LBRACKET       =0x1A,
	ACKEY_RBRACKET       =0x1B,
	ACKEY_SEMICOLON      =0x27,
	ACKEY_APOSTROPHE     =0x28,
	ACKEY_GRAVE          =0x29,
	ACKEY_BACKSLASH      =0x2B,
	ACKEY_COMMA          =0x33,
	ACKEY_PERIOD         =0x34,
	ACKEY_SLASH          =0x35,
						 	  
// CHARACTER KEYS		 	  
	ACKEY_A              =0x41,
	ACKEY_B              =0x42,
	ACKEY_C              =0x43,
	ACKEY_D              =0x44,
	ACKEY_E              =0x45,
	ACKEY_F              =0x46,
	ACKEY_G              =0x47,
	ACKEY_H              =0x48,
	ACKEY_I              =0x49,
	ACKEY_J              =0x4A,
	ACKEY_K              =0x4B,
	ACKEY_L              =0x4C,
	ACKEY_M              =0x4D,
	ACKEY_N              =0x4E,
	ACKEY_O              =0x4F,
	ACKEY_P              =0x50,
	ACKEY_Q              =0x51,
	ACKEY_R              =0x52,
	ACKEY_S              =0x53,
	ACKEY_T              =0x54,
	ACKEY_U              =0x55,
	ACKEY_V              =0x56,
	ACKEY_W              =0x57,
	ACKEY_X              =0x58,
	ACKEY_Y              =0x59,
	ACKEY_Z              =0x5A,

						 	  
// MAIN NUM KEYS		 	  
	ACKEY_1              =0x02,
	ACKEY_2              =0x03,
	ACKEY_3              =0x04,
	ACKEY_4              =0x05,
	ACKEY_5              =0x06,
	ACKEY_6              =0x07,
	ACKEY_7              =0x08,
	ACKEY_8              =0x09,
	ACKEY_9              =0x0A,
	ACKEY_0              =0x0B,
};

#endif