copy debug\Engine.lib ..\ActionEditor\ACEditor\bin\Debug;
copy debug\EngineMath.lib ..\ActionEditor\ACEditor\bin\Debug;
copy debug\EngineCommon.lib ..\ActionEditor\ACEditor\bin\Debug;

copy debug\ACD3DEngine.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\ACOPENALEngine.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\ACWSEngine.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\ACDIEngine.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\EngineWrapper.dll ..\ActionEditor\ACEditor\bin\Debug;

copy debug\ConfigurationFile.ini ..\ActionEditor\ACEditor\bin\Debug;


copy debug\ogg.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\ogg_d.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\vorbis.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\vorbis_d.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\vorbisenc.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\vorbisenc_d.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\vorbisfile.dll ..\ActionEditor\ACEditor\bin\Debug;
copy debug\vorbisfile_d.dll ..\ActionEditor\ACEditor\bin\Debug;